### ISSUE TITLE
Error: php artisan super:admin --username=ibnudirsan --email=ibnudirsan@gmail.com --password=Password@123

### ISSUE THREAD

**Issue by xsamprasanna** [IDrumahdev/Starter-Kit-Laravel-9#2]
When Enter This command got the Error
 php artisan super:admin --username=ibnudirsan --email=ibnudirsan@gmail.com --password=Password@123

   ERROR  An error occurred in Superadmin account setup.

..:: Created by RumahDev ::..

**Comment by IDrumahdev** [comment]
Have you run the command 
php artisan db:seed --class=PermissionSeeder ?.

**Comment by catwhocode** [comment]
I got similar error when invoking super:admin after running PermissionSeeder

**Comment by IDrumahdev** [comment]
Have you created Database and Configuration in the env?  I want to know what version of PHP are you using?

**Comment by catwhocode** [comment]
yes, all tables have been created after migration, I use PHP 8.1.6

**Comment by IDrumahdev** [comment]
try to find the php file namespace App\Console\Commands\SuperAdmin.php
and comment on the share
DB::beginTransaction();
        try {

And

        } catch (\Exception $e) {
            DB::rollBack();
            $this->components->error('An error occurred in Superadmin account setup.');
            $this->line('<bg=black;fg=white>..:: Created by RumahDev ::..</>');
        } finally {
            DB::commit();
        }
        
        
        then restart the command php artisan db:seed --class=PermissionSeeder

**Comment by catwhocode** [comment]
solved, I forgot to run php artisan key:generate

**Comment by IDrumahdev** [comment]
Oke.. 
success always for you...

**Comment by xsamprasanna** [comment]
Thanks @IDrumahdev 
after comment that line, Now it's working
