### ISSUE TITLE
Masalah membuat akun Superadmin

### ISSUE THREAD

**Issue by bagushermawan** [IDrumahdev/Starter-Kit-Laravel-9#3]
bang apa harus pake 'php artisan super:admin --username=ibnudirsan --email=ibnudirsan@gmail.com --password=Password@123
' soalnya saya buat manual mesti error ga bisa login

**Comment by IDrumahdev** [comment]
Iya.. harus pakai CLI itu karena ada proses membuatan role and permission..

**Comment by bagushermawan** [comment]
> Iya.. harus pakai CLI itu karena ada proses membuatan role and permission..

Abis itu mesti verif email itu juga bang buat nyobain fitur yang lain

**Comment by IDrumahdev** [comment]
Tidak harus..
Itu masih ada bug dikit..
Di by pass di database nya saja..
Di tabel user pada filed verifikasi_at di isi tanggal sekarang aja..
Next time di generate ketika pake CLI itu..
